### PR TITLE
remove tempfile outside the with block

### LINKED ISSUE #23: PermissionError: [WinError 32] The process cannot access the file because it is being used by another  process
On Win10 with py3.8 I get the error when running the hook.

`.pre-commit-config.yaml` config (shorted):
```yaml
...
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: 8cccd08a2ddd47f0e995302b08655320fd04981a # frozen: v1.2.3
    hooks:
      - id: python-safety-dependencies-check
        args: ["--full-report"]
        files: pyproject.toml
        exclude: bin/.*
...
```

Stacktrace (shorted):
```text
safety...................................................................Failed
- hook id: python-safety-dependencies-check
- exit code: 1

+==============================================================================+
|                                                                              |
|                               /$$$$$$            /$$                         |
|                              /$$__  $$          | $$                         |
|           /$$$$$$$  /$$$$$$ | $$  \__//$$$$$$  /$$$$$$   /$$   /$$           |
|          /$$_____/ |____  $$| $$$$   /$$__  $$|_  $$_/  | $$  | $$           |
|         |  $$$$$$   /$$$$$$$| $$_/  | $$$$$$$$  | $$    | $$  | $$           |
|          \____  $$ /$$__  $$| $$    | $$_____/  | $$ /$$| $$  | $$           |
|          /$$$$$$$/|  $$$$$$$| $$    |  $$$$$$$  |  $$$$/|  $$$$$$$           |
|         |_______/  \_______/|__/     \_______/   \___/   \____  $$           |
|                                                          /$$  | $$           |
|                                                         |  $$$$$$/           |
|  by pyup.io                                              \______/            |
|                                                                              |
+==============================================================================+
| REPORT                                                                       |
| checked 160 packages, using free DB (updated once a month)                   |
+==============================================================================+
| No known security vulnerabilities found.                                     |
+==============================================================================+
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code  
    exec(code, run_globals)
  File "C:\Users\<username>\.cache\pre-commit\repo1t7i50ag\py_env-python3.8\Scripts\safety_check.EXE\__main__.py", line 7, in <module>
  File "C:\Users\<username>\.cache\pre-commit\repo1t7i50ag\py_env-python3.8\lib\site-packages\pre_commit_hooks\safety_check.py", line 46, in main
    return call_safety_check([tmp_requirements.name], parsed_args.ignore, parsed_args.full_report, args_rest)
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\Users\<username>\.cache\pre-commit\repo1t7i50ag\py_env-python3.8\lib\site-packages\pre_commit_hooks\safety_check.py", line 81, in convert_poetry_to_requirements
    os.remove(ntf.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another 
process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpsp4pt95s'
```

AFAIK you cannot remove a file on windows while it is open and exactly this happens here.
The issue is that the removal of the temp file happens within the `with` block.

https://github.com/Lucas-C/pre-commit-hooks-safety/blob/master/pre_commit_hooks/safety_check.py#L74-L81

I tested a quick fix locally and got it to work. I will make a PR right away.

### PR DESCRIPTION
**Pull request by Cielquan**
fixes #23

### CODE REVIEW

**Comment by Cielquan** [comment]
Made the change on github. Will make a quick clone and run pre-commit + tests to be sure everything is fine.

**Comment by Cielquan** [comment]
pre-commit is green.

Ran tests with py3.8.

```text
tests\safety_test.py ..............X...                                                                                                                                                                                   [100%]

---------- coverage: platform win32, python 3.8.10-final-0 -----------
Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
pre_commit_hooks\__init__.py           0      0   100%
pre_commit_hooks\safety_check.py      67      7    90%   47-49, 63, 70-72, 100
----------------------------------------------------------------
TOTAL                                 67      7    90%

Required test coverage of 89% reached. Total coverage: 89.55%
```

Ran the tests also on `master` and those three tests failed because of the issue I fix in this PR.
```text
FAILED tests/safety_test.py::test_pyproject_toml_without_deps - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpq...
FAILED tests/safety_test.py::test_pyproject_toml_with_ko_deps - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmpb...
FAILED tests/safety_test.py::test_pyproject_toml_with_ko_dev_deps - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\...
```

**Comment by Lucas-C** [comment]
Thank you for the fix!
This was released in [v1.2.4](https://github.com/Lucas-C/pre-commit-hooks-safety/releases/tag/v1.2.4))

**Comment by Cielquan** [comment]
Thanks for the fast merge 👍🏾

**Pull request merged**
