### PR TITLE
Allow selection of additional dependency groups - fix #44

### LINKED ISSUE #44: Hook fails because there are no dev dependency group in our poetry config
We have chosen to split our dependencies more than just a main and a dev group, so now we do not have a dev group at all.
Instead we have `main`, `docs`, `lint`, `tools` and `test`.

In Poetry 1.5.0, this now breaks because https://github.com/python-poetry/poetry/pull/7529 was merged and unknown group names now trigger an error in poetry when used with `--only`, `--with` and `--without`.

Would it be possible to have the full list of optional groups be taken as an argument? This would also help with #41

### PR DESCRIPTION
**Pull request by kurthaegeman**
Modified the `build_parser()` and `convert_poetry_to_requirements()` functions to allow for the selection of additional dependency groups.

With this PR, the `dev` group is no longer automatically selected, which is a change in behaviour compared to previous version, but will avoid errors on projects that do not have this group.

### CODE REVIEW

**Comment by kurthaegeman** [comment]
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python`

That URL has changed. Do you have [any preference](https://python-poetry.org/docs/#ci-recommendations) for its replacement? `pip install` or `install.python-poetry.org`?

**Comment by Lucas-C** [comment]
Thank you for this contribution!
And sorry for the answer delay 😅

This seems very promising, and I'd be happy to merge this soon.

There is just a minor problem with this PR: you added files in a `build/` subdirectory instead of editing the existing files in `pre_commit_hooks/` & `tests/`

> That URL has changed. Do you have [any preference](https://python-poetry.org/docs/#ci-recommendations) for its replacement? `pip install` or `install.python-poetry.org`?

As you wish!

**Comment by kurthaegeman** [comment]
> There is just a minor problem with this PR: you added files in a build/ subdirectory instead of editing the existing files in pre_commit_hooks/ & tests/

Yes, it seems I missed that when cleaning up. I added the `build` folder to `.gitignore`, removed it and did a force push.

The existing files in `pre_commit_hooks` and `tests` were properly edited. The unwanted folder just contained copies. `pytest` and `pre-commit run --all-files` still in the green.

**Comment by Lucas-C** [comment]
Merged! Thank you for your contribution @kurthaegeman 👍

**Comment by kurthaegeman** [comment]
You're welcome!

**Pull request merged**
